### ISSUE TITLE
Always set background

### ISSUE THREAD

**Issue by giorni** [fenetikm/falcon#13]
Are there any reason to not always set the background color as default, but only within a gui? 

```viml
" from falcon/plugin/falcon.vim  

" Put in a background colour for gui
if has("gui_running")
  hi Normal guifg=#d4d4d9 ctermfg=188 guibg=#0b0b1a ctermbg=233 gui=NONE cterm=NONE
  hi NonText guifg=#3e3e40 ctermfg=237 guibg=#0b0b1a ctermbg=233 gui=NONE cterm=NONE
endif
```

**Comment by fenetikm** [comment]
Yeah - the reason is that in the terminal you can then have the concept of an _active_ window vs an _inactive_ one. So when you have multiple windows and/or splits in the one terminal session you can differentiate which one you are currently typing into at a glance.

In a GUI this makes less sense so that's why there is that check for a gui.

Having said that feel free to make a PR that adds in an overriding check which will force a background colour, I'll add that as an idea to my TODO.
