### ISSUE TITLE
What's background color in this pic?

### ISSUE THREAD

**Issue by glepnir** [fenetikm/falcon#39]
What's background color in this pic? Thanks .
![image](https://user-images.githubusercontent.com/41671631/95719665-bc667a80-0ca2-11eb-9e21-f770c6954c24.png)

**Comment by anouarkappitou** [comment]
Hello @glepnir,  did you figure out how to change the background to match the one in the attached image ?

**Comment by fenetikm** [comment]
Maybe I could help - there are possibly two background colours - one for the active window/pane and one for the other inactive windows/panes. There are settings to have only one background colour so that there is no difference or you can have both inactive / active. 

What kind of setup are you after @anouarkappitou ?

**Comment by anouarkappitou** [comment]
Hello @fenetikm, thank you for the replay, my intent is to use the color in the background in both situations( active and inactive ).
My setup as for now has only colorscheme declaration:
'''
colorscheme falcon
'''
I'm aware that there is two global variable that in order to enable disable background and also state switching( active/ inactive ).
